[package]
name = "protocolsrv"
edition = "2021"
version = "0.0.1"
authors = ["Luis Soares"]

[dependencies]
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
rand = "0.8.5"
local-ip-address = "0.5.5"